### ISSUE TITLE
I have a question regarding the Arduino circuit diagram.

### ISSUE THREAD

**Issue by rabbitonthemoon** [expectopatronm/platooning-demonstrator#2]
Hello, sir. I am a college student working on a project as a jetbot in Korea. Thanks to the high-quality sources you posted, we are working on the project easily.
I'm contacting you because I couldn't find the Arduino circuit diagram on the GitHub you uploaded. Could you share the Arduino circuit diagram? If I have it, it will be very helpful for me and my team to study. I'll be waiting for the reply. Thank you :)

**Comment by expectopatronm** [comment]
Hi @rabbitonthemoon, Awesome that you decided to work on this project. Regarding the Arduino connections, I don't have the circuit diagram ready at hand since this project is already pretty old, but I will see what I can come up with and get back to you with a rough circuit diagram. Feel free to contact me if you face any further issues.

**Comment by rabbitonthemoon** [comment]
Hello!
Thank you very much for your quick feedback. I'll be waiting for your reply. Thank you.

**Comment by expectopatronm** [comment]
Hi again,  I unfortunately do not have the circuit diagram ready, but what I can tell you is that the circuit is fairly simple, you just need to connect a LCD display to the Arduino, which is a straightforward standard connection available in any arduino website. you then also have two simple servos that control the pan and tilt of the front camera, which is again a very simple standard connection. The third is the serial communication between the arduino and the Jetson, which is also pretty straightforward. what I would suggest is using the assigned pins from the code to figure out what goes where. Good luck!

**Comment by rabbitonthemoon** [comment]
Hello, your reply was very helpful. Thank you for your good advice, and I was able to study a lot thanks to you! I'm a little late in greeting, but I'd like to thank you. Have a nice day :)

나의 iPhone에서 보냄

**Comment by expectopatronm** [comment]
That’s good to hear :) let me know if you need any further help with the project. On 16. Oct 2022, at 20:49, rabbitonthemoon ***@***.***> wrote:﻿
Hello, your reply was very helpful. Thank you for your good advice, and I was able to study a lot thanks to you! I'm a little late in greeting, but I'd like to thank you. Have a nice day :)

나의 iPhone에서 보냄
